### ISSUE TITLE
Crash on newer android OS-es

### ISSUE THREAD

**Issue by mariusCujo** [bastienpaulfr/Treessence#14]
Caused by: java.nio.file.FileSystemException: fileg.log.0.lck: Read-only file system
        at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177)
        at java.nio.channels.FileChannel.open(FileChannel.java:287)
        at java.nio.channels.FileChannel.open(FileChannel.java:335)
        at java.util.logging.FileHandler.openFiles(FileHandler.java:460)
        at java.util.logging.FileHandler.<init>(FileHandler.java:403)

**Comment by osipxd** [comment]
Looks like duplicate of #11
