### ISSUE TITLE
java.nio.file.FileSystemException: log.0.lck: Read-only file system

### ISSUE THREAD

**Issue by hiddeneyes02** [bastienpaulfr/Treessence#9]
I am trying to implement file logging into my app, but the library couldn't create log file 

     try {
         Timber.Tree fileTree = new FileLoggerTree.Builder()
               .withFileLimit(5)
               .withMinPriority(Log.DEBUG)
               .appendToFile(true)
               .build();

         Timber.plant(fileTree);
      } catch (IOException e) {
         e.printStackTrace();
      }

```
W/System.err: java.nio.file.FileSystemException: log.0.lck: Read-only file system
W/System.err:     at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177)
W/System.err:     at java.nio.channels.FileChannel.open(FileChannel.java:287)
W/System.err:     at java.nio.channels.FileChannel.open(FileChannel.java:335)
W/System.err:     at java.util.logging.FileHandler.openFiles(FileHandler.java:460)
W/System.err:     at java.util.logging.FileHandler.<init>(FileHandler.java:403)
W/System.err:     at fr.bipi.tressence.file.FileLoggerTree$Builder.build(FileLoggerTree.java:242)
W/System.err:     at com.myapp.Application.onCreate(Application.java:23)
W/System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189)
W/System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6867)
W/System.err:     at android.app.ActivityThread.access$1600(ActivityThread.java:242)
W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2063)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7830)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1040)
```

**Comment by bastienpaulfr** [comment]
Hi,

You should add a directory explicitely

```java
try {
     Timber.Tree fileTree = new FileLoggerTree.Builder()
            // ---
            .withDirName("someExistingDir")
            // ---
           .withFileLimit(5)
           .withMinPriority(Log.DEBUG)
           .appendToFile(true)
           .build();

     Timber.plant(fileTree);
  } catch (IOException e) {
     e.printStackTrace();
  }

```
